# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f1deaf70045e9085948c7bbdfb1b497e589f714ed3faff5f48585ae978a84ab42d6547401c187441c55c76b65f7214773f56963194f162465031edb5156c383

test:
  secret_key_base: 49a5c76e860c1e72043563ceb68877808141f2d307ec892fdcc5bd5917cde09c4d6e73fe364ae8fc687618037cf29c6e98d99d4ecdab8d563af1f50b194e4154

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
